// Pula celów do losowania na planszę. Edytuj tę listę — to jedyne źródło treści gry.
window.GOALS = [
  "Zrób 20 przysiadów",
  "Zrób 15 pompek (kolana OK)",
  "Przebiegnij 100 m",
  "Zrób mostek i utrzymaj 10 s",
  "Wymień 5 punktów Prawa Harcerskiego",
  "Zaśpiewaj zwrotkę pieśni harcerskiej",
  "Zawiąż węzeł ratowniczy",
  "Zawiąż węzeł żeglarski",
  "Pokaż, jak składa się chustę na trójkąt",
  "Wymień 3 węzły i do czego służą",
  "Nazwij 5 gwiazdozbiorów",
  "Wskaż na niebie Wielki Wóz (lub opisz)",
  "Wymień 4 strony świata",
  "Narysuj prostą mapę okolicy z 3 punktami",
  "Zrób kompas z igły i liścia (opisz kroki)",
  "Wymień 5 zasad bezpieczeństwa przy ognisku",
  "Rozpal ognisko bez zapalniczki (opisz metodę)",
  "Przygotuj kanapkę dla drużyny (rola szefa kuchni)",
  "Wymień 3 rośliny jadalne rosnące w lesie",
  "Rozpoznaj 3 drzewa po liściach / korze",
  "Opowiedz anegdotę z biwaku (max 1 min)",
  "Zrób 10 pajacyków",
  "Utrzymaj deskę 30 sekund",
  "Przekaż tajną wiadomość szeptem łańcuchem",
  "Zrób portret kolegi z drużyny (30 s)",
  "Wymień 3 stopnie harcerskie młodsze od Twojego",
  "Wyrecytuj Przyrzeczenie Harcerskie",
  "Pokaż salut harcerski i wyjaśnij znaczenie",
  "Zaproponuj grę na 5 minut dla zastępu",
  "Ułóż hasło zastępu z 3 słów",
  "Znajdź coś zielonego w 20 sekund",
  "Znajdź coś okrągłego w 20 sekund",
  "Policz do 20 w języku obcym",
  "Nazwij stolicę 5 krajów europejskich",
  "Wymień 4 pory roku i typową aktywność harcerską",
  "Zrób 5 przysiadów + 5 pajacyków bez przerwy",
  "Wyjaśnij, co to jest zastęp",
  "Wyjaśnij, co to jest drużyna",
  "Wymień 3 rzeczy w apteczce osobistej",
  "Pokaż pozycję bezpieczną (boczną)",
  "Zadzwoń pod numer alarmowy — odtwórz rozmowę (fikcyjną)",
  "Wymień 3 zasady Leave No Trace",
  "Zapakuj plecak na jednodniową wycieczkę (opisz listę)",
  "Zrób knot z sznurka i zapal go (pod nadzorem)",
  "Ułóż zdanie z liter swojego imienia",
  "Zagraj w papier-kamień-nożyce z sąsiadem — 3 rundy",
  "Wymień 5 instrumentów muzycznych",
  "Zatańcz 15 sekund do wybranej piosenki",
  "Opisz drogę z domu na zbiórkę w 5 zdaniach",
  "Wymień 3 cele zbiórki (dowolne, sensowne)",
];
